# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('current_state', models.CharField(choices=[(b'PENDING', b'PENDING'), (b'LOCKING_ACCOUNT', b'LOCKING_ACCOUNT'), (b'LOCKING_COMPLETE', b'LOCKING_COMPLETE'), (b'RETIRING_CREDENTIALS', b'RETIRING_CREDENTIALS'), (b'CREDENTIALS_COMPLETE', b'CREDENTIALS_COMPLETE'), (b'RETIRING_ECOM', b'RETIRING_ECOM'), (b'ECOM_COMPLETE', b'ECOM_COMPLETE'), (b'RETIRING_FORUMS', b'RETIRING_FORUMS'), (b'FORUMS_COMPLETE', b'FORUMS_COMPLETE'), (b'RETIRING_EMAIL_LISTS', b'RETIRING_EMAIL_LISTS'), (b'EMAIL_LISTS_COMPLETE', b'EMAIL_LISTS_COMPLETE'), (b'RETIRING_ENROLLMENTS', b'RETIRING_ENROLLMENTS'), (b'ENROLLMENTS_COMPLETE', b'ENROLLMENTS_COMPLETE'), (b'RETIRING_NOTES', b'RETIRING_NOTES'), (b'NOTES_COMPLETE', b'NOTES_COMPLETE'), (b'NOTIFYING_PARTNERS', b'NOTIFYING_PARTNERS'), (b'PARTNERS_NOTIFIED', b'PARTNERS_NOTIFIED'), (b'RETIRING_LMS', b'RETIRING_LMS'), (b'LMS_COMPLETE', b'LMS_COMPLETE'), (b'ERRORED', b'ERRORED'), (b'ABORTED', b'ABORTED'), (b'COMPLETE', b'COMPLETE')], max_length=25)),
                ('last_state', models.CharField(blank=True, choices=[(b'PENDING', b'PENDING'), (b'LOCKING_ACCOUNT', b'LOCKING_ACCOUNT'), (b'LOCKING_COMPLETE', b'LOCKING_COMPLETE'), (b'RETIRING_CREDENTIALS', b'RETIRING_CREDENTIALS'), (b'CREDENTIALS_COMPLETE', b'CREDENTIALS_COMPLETE'), (b'RETIRING_ECOM', b'RETIRING_ECOM'), (b'ECOM_COMPLETE', b'ECOM_COMPLETE'), (b'RETIRING_FORUMS', b'RETIRING_FORUMS'), (b'FORUMS_COMPLETE', b'FORUMS_COMPLETE'), (b'RETIRING_EMAIL_LISTS', b'RETIRING_EMAIL_LISTS'), (b'EMAIL_LISTS_COMPLETE', b'EMAIL_LISTS_COMPLETE'), (b'RETIRING_ENROLLMENTS', b'RETIRING_ENROLLMENTS'), (b'ENROLLMENTS_COMPLETE', b'ENROLLMENTS_COMPLETE'), (b'RETIRING_NOTES', b'RETIRING_NOTES'), (b'NOTES_COMPLETE', b'NOTES_COMPLETE'), (b'NOTIFYING_PARTNERS', b'NOTIFYING_PARTNERS'), (b'PARTNERS_NOTIFIED', b'PARTNERS_NOTIFIED'), (b'RETIRING_LMS', b'RETIRING_LMS'), (b'LMS_COMPLETE', b'LMS_COMPLETE'), (b'ERRORED', b'ERRORED'), (b'ABORTED', b'ABORTED'), (b'COMPLETE', b'COMPLETE')], max_length=25)),
                ('responses', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
